
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';

export const FETCH_ACTIVITIES = 'FETCH_ACITIVITIES';
export const FETCH_ACTIVITIES_ERROR = 'FETCH_ACTIVITIES_ERROR';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR';
export const SELECT_ACTIVITY = 'SELECT_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_ERROR = 'UPDATE_ACTIVITY_ERROR';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const DELETE_ACTIVITY_ERROR = 'DELETE_ACTIVITY_ERROR';
